fastlane_version "2.55.0"
default_platform :mac

platform :mac do

  before_all do
    #ensure_git_status_clean
    #verify_xcode
  end

  desc "Run tests"
  lane :test do
    scan(formatter: 'xcpretty-json-formatter')
  end

  desc "Install dependencies"
  lane :dependencies do
    carthage(command: "bootstrap", use_ssh: true, cache_builds: true)
  end

  desc "Run linter"
  lane :lint do
    swiftlint(strict: true, config_file: ".swiftlint.yml")
  end

  desc "Code coverage report"
  lane :coverage_report do
    xcov(minimum_coverage_percentage: 100.0)
  end

  desc "Danger comment on PR"
  lane :pr_comment do
    danger(fail_on_errors: true)
  end

  desc "Generate documentation"
  lane :documentation do
    jazzy
  end

  desc "Test and gather coverage report"
  lane :coverage do
    test
    coverage_report
  end

  desc "Install dependencies, test, lint and write PR comment"
  lane :ci do
    dependencies
    lint
    test
    pr_comment # includes coverage
  end

  after_all do |lane|
    notification(message: "Fastlane finished '#{lane}'")
  end

end
